spring:
  profiles:
    active: dev
    include:
      - console-logging
      - file-logging
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_food?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: xoghk
    password: dlxoghk
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: INFO
    delivery-food: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: C://logs/spring-boot-log/delivery-food
