spring:
  profiles:
    active: dev
    include:
      - console-logging
      - file-logging
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery_food?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: xoghk
    password: dlxoghk
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1095288292737-me0kh7om3afgbg9eea7m2ogjj9dlft2h.apps.googleusercontent.com
            client-secret: SdAMzKonD9G2CCQKPG7uMS2T
            # redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope: email, profile

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: xoghk0321@gmail.com
    password: fnhfrojbuhcztllr
    port: 587
    protocol: smtp
    debug: true
    smtp:
      auth: true
      starttls:
        enable: true
    emailVerificationTokenExpiration: 1800000

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

app:
  jwt:
    secret: ei987dbfiowee09f
    accessTokenExpiration: 25920000000 # 300일
    refreshTokenExpiration: 2592000000 # 30일
    header:
      name: Authorization
      prefix: Bearer

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

  velocity:
    templates:
      location: /templates/

logging:
  level:
    root: INFO
    delivery-food: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: C://logs/spring-boot-log/delivery-food
